server:
  port: 8888

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
#    设置缓存为false 为了热部署 host refresh
    cache: false
#    设置freemarker
  freemarker:
    allow-request-override: false
#    开发过程建议关闭缓存
    cache: false
    check-template-location: false
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
#    prefix: xx
    request-context-attribute:
#    settings:
# 默认后缀就是.ftl
#    suffix: .ftl
#    template-loader-path: classPath:/templates/
#    view-names:

#热部署生效
spring.devtools.restart.enabled: true
#设置重启的目录
#spring.devtools.restart.additional-paths: src/main/java
#classpath目录下的WEB-INF文件夹内容修改不重启
spring.devtools.restart.exclude: resources/**

#配置返回jsp start
# 配置jsp文件的位置，默认位置为：src/main/webapp
spring.mvc.view.prefix: /templates/
# 配置jsp文件的后缀
spring.mvc.view.suffix: .jsp
#配置返回jsp end